export const StudentTypes = {
  FETCH_ALL_STUDENT_START: "Student/FETCH_ALL_STUDENT_START",
  FETCH_ALL_STUDENT_FINISH: "Student/FETCH_ALL_STUDENT_FINISH",
  FETCH_MY_STUDENT_START: "Student/FETCH_MY_STUDENT_START",
  FETCH_MY_STUDENT_FINISH: "Student/FETCH_MY_STUDENT_FINISH",
  UPDATE_STUDENT_START: "Student/UPDATE_STUDENT_START",
  UPDATE_STUDENT_FINISH: "Student/UPDATE_STUDENT_FINISH",
};
