export const RecordingTypes = {
  GET_RECORDINGS_START:"Recording/GET_RECORDINGS_START",
  GET_RECORDINGS_FINISH: "Recording/GET_RECORDINGS_FINISH",
  DELETE_RECORDING_START: "Recording/DELETE_RECORDING_START",
  DELETE_RECORDING_FINISH: "Recording/DELETE_RECORDING_FINISH",
  RECORDING_SHOW_HIDE_OPTIONS: "Recording/RECORDING_SHOW_HIDE_OPTIONS",
  RECORDING_STOP: "Recording/RECORDING_STOP",
  RECORDING_START: "Recording/RECORDING_START",
  POSE_ESTIMATION_START: "Recording/POSE_ESTIMATION_START",
  POSE_ESTIMATION_FINISH: "Recording/POSE_ESTIMATION_FINISH",
  GET_RECORDING_BASE_ON_CALIBRATION_START: "Recording/GET_RECORDING_BASE_ON_CALIBRATION_START",
  GET_RECORDING_BASE_ON_CALIBRATION_FINISH: "Recording/GET_RECORDING_BASE_ON_CALIBRATION_FINISH",
  RECORDING_ERROR_START: "Recording/RECORDING_ERROR_START",
  RECORDING_ERROR_FINISH: "Recording/RECORDING_ERROR_FINISH",
  RECORDING_CONVERSION_START: "Recording/CONVERSION_START",
  RECORDING_CONVERSION_FINISH: "Recording/CONVERSION_FINISH",
  RECORDING_UPLOAD: "Recording/RECORDING_UPLOAD"
};
