export const FriendsTypes = {
  ADDED_START: "Friends/ADDED_START",
  ADDED_FINISH: "Friends/ADDED_FINISH",
  NOT_ADDED_START: "Friends/NOT_ADDED_START",
  NOT_ADDED_FINISH: "Friends/NOT_ADDED_FINISH",
  SEND_REQUEST_START: "Friends/SEND_REQUEST_START",
  SEND_REQUEST_FINISH: "Friends/SEND_REQUEST_FINISH",
  ACCEPT_REQUEST_START: "Friends/ACCEPT_REQUEST_START",
};
