export const AnglesTypes = {
  ANGLES_LOAD: "Angles/ANGLES_LOAD",
  ANGLES_ADD: "Angles/ANGLES_ADD",
  ANGLES_DELETE: "Angles/ANGLES_DELETE",
  ANGLES_DELETE_ALL: "Angles/ANGLES_DELETE_ALL",
  ANGLES_GENERATE_CHART_START: "Angles/ANGLES_GENERATE_CHART_START",
  ANGLES_GENERATE_CHART_FINISH: "Angles/ANGLES_GENERATE_CHART_FINISH",
  ANGLES_RESTART: "Angles/ANGLES_RESTART",
};
