export const CalibrationTypes = {
    CALIBRATION_SEND_IMAGE_START: "calibration/CALIBRATION_SEND_IMAGE_START",
    CALIBRATION_SEND_IMAGE_FINISH: "calibration/CALIBRATION_SEND_IMAGE_FINISH",
    CALIBRATION_DELETE_START:"calibration/CALIBRATION_DELETE_START",
    CALIBRATION_DELETE_FINISH:"calibration/CALIBRATION_DELETE_FINISH",
    CALIBRATION_FAIL: "calibration/CALIBRATION_FAIL",
    CALIBRATION_RESET: "calibration/CALIBRATION_RESET",
    CALIBRATION_GET_ALL_START: "calibration/CALIBRATION_GET_ALL_START",
    CALIBRATION_GET_ALL_FINISH: "calibration/CALIBRATION_GET_ALL_FINISH",
    CALIBRATION_PYTHON_START: "calibration/CALIBRATION_PYTHON_START",
    CALIBRATION_PYTHON_FINISH: "calibration/CALIBRATION_PYTHON_FINISH",
    CALIBRATION_GET_ID_START: "calibration/CALIBRATION_GET_ID_START",
    CALIBRATION_GET_ID_FINISH: "calibration/CALIBRATION_GET_ID_FINISH",
  };
  